<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Card; use App\Models\Board; use App\Models\Activity; use Illuminate\Http\Request;
class CardController extends Controller {
 public function store(Request $r, Board $board){$this->authorize('update',$board);$data=$r->validate(['kanban_list_id'=>'required|exists:kanban_lists,id','title'=>'required|max:255','description'=>'nullable','type'=>'in:task,note','priority_id'=>'nullable|exists:priorities,id','assignee_id'=>'nullable|exists:users,id','due_date'=>'nullable|date','start_date'=>'nullable|date','estimated_hours'=>'nullable|numeric','tag_ids'=>'array']);$card=Card::create($data+['board_id'=>$board->id,'created_by'=>$r->user()->id,'position'=>Card::where('kanban_list_id',$data['kanban_list_id'])->max('position')+1]);$card->tags()->sync($data['tag_ids']??[]);Activity::create(['user_id'=>$r->user()->id,'action'=>'card.created','entity_type'=>Card::class,'entity_id'=>$card->id]);return $card->load('tags','priority','assignee');}
 public function update(Request $r, Card $card){$this->authorize('update',$card->board);$data=$r->validate(['title'=>'sometimes|max:255','description'=>'nullable','type'=>'in:task,note','status'=>'in:open,in_progress,review,done,archived','priority_id'=>'nullable|exists:priorities,id','assignee_id'=>'nullable|exists:users,id','due_date'=>'nullable|date','start_date'=>'nullable|date','estimated_hours'=>'nullable|numeric','tag_ids'=>'array']);$card->update($data); if(array_key_exists('tag_ids',$data))$card->tags()->sync($data['tag_ids']); Activity::create(['user_id'=>$r->user()->id,'action'=>'card.updated','entity_type'=>Card::class,'entity_id'=>$card->id,'properties'=>$data]);return $card->load('tags','priority','assignee');}
 public function move(Request $r, Card $card){$this->authorize('update',$card->board);$data=$r->validate(['kanban_list_id'=>'required|exists:kanban_lists,id','position'=>'required|integer|min:0','status'=>'nullable|in:open,in_progress,review,done,archived']);$card->update($data);Activity::create(['user_id'=>$r->user()->id,'action'=>'card.moved','entity_type'=>Card::class,'entity_id'=>$card->id,'properties'=>$data]);return $card;}
 public function destroy(Card $card){$this->authorize('update',$card->board);$card->delete();return response()->noContent();}
}
